import { getDb } from "../db/index.js";
import type { MemoryTier } from "../types.js";

export interface SaveMemoryArgs {
  agentId: string;
  content: string;
  category?: MemoryTier;
  keywords?: string;
  sector?: string;
  autoGenerated?: boolean;
}

export function saveMemory(a: SaveMemoryArgs): number {
  const r = getDb()
    .prepare(
      `INSERT INTO memories (agent_id, category, content, keywords, sector, auto_generated)
       VALUES (?, ?, ?, ?, ?, ?)`
    )
    .run(a.agentId, a.category ?? "warm", a.content, a.keywords ?? null, a.sector ?? null, a.autoGenerated ? 1 : 0);
  return Number(r.lastInsertRowid);
}

export interface SearchArgs {
  agentId?: string;
  q?: string;
  /** one tier, or a set of tiers (IN-filtered) — e.g. ['hot','warm'] for the always-bundle */
  category?: MemoryTier | MemoryTier[];
  limit?: number;
}

export interface MemoryRow {
  id: number;
  agent_id: string;
  category: string;
  content: string;
  keywords: string | null;
  salience: number;
  created_at: number;
  accessed_at: number;
}

/** FTS5 search when `q` is given; otherwise most-recent, filterable by agent/category. */
export function searchMemories(a: SearchArgs): MemoryRow[] {
  const db = getDb();
  const limit = Math.min(a.limit ?? 50, 500);
  const where: string[] = [];
  const params: unknown[] = [];

  if (a.q && a.q.trim()) {
    where.push("m.id IN (SELECT rowid FROM memories_fts WHERE memories_fts MATCH ?)");
    params.push(ftsQuery(a.q));
  }
  if (a.agentId) {
    where.push("m.agent_id = ?");
    params.push(a.agentId);
  }
  if (a.category) {
    // single tier -> "= ?"; a set -> "IN (?,?,…)". Both hit idx_memories_agent_cat(agent_id, category).
    const cats = Array.isArray(a.category) ? a.category : [a.category];
    if (cats.length) {
      where.push(`m.category IN (${cats.map(() => "?").join(",")})`);
      params.push(...cats);
    }
  }
  const clause = where.length ? `WHERE ${where.join(" AND ")}` : "";
  params.push(limit);
  return db
    .prepare(
      `SELECT m.id, m.agent_id, m.category, m.content, m.keywords, m.salience, m.created_at, m.accessed_at
       FROM memories m ${clause} ORDER BY m.created_at DESC LIMIT ?`
    )
    .all(...params) as MemoryRow[];
}

/** Sanitize free text into a safe FTS5 MATCH query (quoted terms, OR-joined). */
function ftsQuery(q: string): string {
  const terms = q
    .toLowerCase()
    .replace(/["()*]/g, " ")
    .split(/\s+/)
    .filter(Boolean)
    .map((t) => `"${t}"`);
  return terms.length ? terms.join(" OR ") : `""`;
}
